format_code_in_doc_comments=true
format_macro_matchers=true
format_strings=true
match_block_trailing_comma=true
imports_granularity="Crate"
reorder_impl_items=true
use_field_init_shorthand=true
wrap_comments=true
