---
name: CI

"on": [push, pull_request]

env:
  PROPTEST_CASES: 20000

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        run: rustup toolchain install  --profile minimal --component clippy,rustfmt --no-self-update --override nightly
      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Run rustfmt
        run: cargo fmt -- --check

  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-none
          - aarch64-unknown-none
          - thumbv7m-none-eabi
        toolchain:
          - stable
          - nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        run: rustup toolchain install --target ${{ matrix.target }} --no-self-update --override ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

  test:
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        run: rustup toolchain install --no-self-update --override ${{ matrix.toolchain }}
      - name: Run tests
        run: cargo test
